### ISSUE TITLE
The `code` and `ids_properties` are filled with empty strings

### ISSUE THREAD

**Issue by orso82** [transp/transp-imas-translator#7]
These IDSs are present, but they have empty fields rather than the strings that one would expect

**Comment by transp** [comment]
To avoid redundancy, can we set the relevant strings in the Summary IDS only? For example:
sum%ids_properties%comment = 'Data translated by transp2imas'
sum%code%name = 'TRANSP'

**Comment by SimonPinches** [comment]
I think you should fill all of the `code`  and `ids_properties` fields in all of the IDSs so that this information is available downstream when only one IDS is read.  We should also capture both the name and commit hash of this translator code as well as that of TRANSP itself to have a more complete capture of the data's provenance.

**Comment by transp** [comment]
Comments are now written to every IDS. The git hash for the translator is used as the version number. TRANSP output does currently not have any version info.
